/*
 * GENERATED by scripts/gen-effect-enums.mjs on After Effects 26.0x67 - do not edit.
 * Popup options for built-in effect parameters, keyed by parameter matchName;
 * option N (1-based) is the value AE stores. AE has no API for this table.
 */
var __mcp_effectEnums = {
 "CC Ball Action-0009": [
  "Crisp",
  "Medium",
  "Smooth"
 ],
 "CC Ball Action-0012": [
  "Red",
  "Green",
  "Blue",
  "Brightness",
  "Saturation",
  "RGB",
  "Radius",
  "Diamond",
  "Spherize"
 ],
 "CC Ball Action-0004": [
  "X Axis",
  "Y Axis",
  "Center X",
  "Center Y",
  "Radius",
  "Random",
  "Red",
  "Green",
  "Blue",
  "Brightness",
  "Diamond",
  "Rectangular",
  "Fast Top"
 ],
 "CC Ball Action-0002": [
  "X",
  "Y",
  "Z",
  "XY",
  "XZ",
  "YZ",
  "XYZ",
  "X15Z",
  "XY15Z"
 ],
 "CC Bend It-0004": [
  "None",
  "Static",
  "Bend",
  "Mirror"
 ],
 "CC Bend It-0005": [
  "Legal",
  "Extended"
 ],
 "CC Bender-0002": [
  "Bend",
  "Marilyn",
  "Sharp",
  "Boxer"
 ],
 "CC Blobbylize-0003": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness"
 ],
 "CC Blobbylize-0022": [
  "Effect Light",
  "AE Lights"
 ],
 "CC Blobbylize-0010": [
  "Distant Light",
  "Point Light"
 ],
 "CC Bubbles-0006": [
  "Liquid",
  "Metal"
 ],
 "CC Bubbles-0007": [
  "None",
  "Lighten",
  "Darken",
  "Fade Inwards",
  "Fade Outwards"
 ],
 "CC Color Offset-0004": [
  "Wrap",
  "Solarize",
  "Polarize"
 ],
 "CC Composite-0002": [
  "Copy",
  "Behind",
  "In front",
  "(-",
  "Darken",
  "Multiply",
  "Linear Burn",
  "Color Burn",
  "Classic Color Burn",
  "(-",
  "Add",
  "Lighten",
  "Screen",
  "Linear Dodge",
  "Color Dodge",
  "Classic Color Dodge",
  "(-",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "Linear Light",
  "Vivid Light",
  "Pin Light",
  "Hard Mix",
  "(-",
  "Difference",
  "Classic Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity",
  "(-",
  "Stencil Alpha",
  "Stencil Luma",
  "Silhouette Alpha",
  "Silhouette Luma",
  "(-",
  "Add Alpha",
  "Luminescent Premul"
 ],
 "CC Cylinder-0027": [
  "XYZ",
  "XZY",
  "YXZ",
  "YZX",
  "ZXY",
  "ZYX"
 ],
 "CC Cylinder-0013": [
  "Full",
  "Outside",
  "Inside"
 ],
 "CC Drizzle-0022": [
  "Effect Light",
  "AE Lights"
 ],
 "CC Drizzle-0010": [
  "Distant Light",
  "Point Light"
 ],
 "CC Environment-0004": [
  "Spherical",
  "Probe",
  "Vertical Cross"
 ],
 "CC Flo Motion-0007": [
  "Low",
  "Medium",
  "High"
 ],
 "CC Force Motion Blur-0004": [
  "On",
  "Off"
 ],
 "CC Glass-0003": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness"
 ],
 "CC Glass-0023": [
  "Effect Light",
  "AE Lights"
 ],
 "CC Glass-0011": [
  "Distant Light",
  "Point Light"
 ],
 "CC Glue Gun-0008": [
  "Plain",
  "Wobbly"
 ],
 "CC Glue Gun-0028": [
  "Effect Light",
  "AE Lights"
 ],
 "CC Glue Gun-0016": [
  "Distant Light",
  "Point Light"
 ],
 "CC Grid Wipe-0006": [
  "Doors",
  "Radial",
  "Rectangular"
 ],
 "CC Hair-0009": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness",
  "Hue",
  "Saturation"
 ],
 "CC Image Wipe-0006": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness",
  "Hue",
  "Saturation"
 ],
 "CC Jaws-0006": [
  "Spikes",
  "RoboJaw",
  "Block",
  "Waves"
 ],
 "CC Kaleida-0003": [
  "Unfold",
  "Wheel",
  "Fish Head",
  "Can Meas",
  "Flip Flop",
  "Flower",
  "Dia Cross",
  "Flipper",
  "Starlish"
 ],
 "CC Light Burst 2.5-0004": [
  "Straight",
  "Fade",
  "Center"
 ],
 "CC Light Rays-0005": [
  "Round",
  "Square"
 ],
 "CC Light Rays-0009": [
  "None",
  "Add",
  "Lighten",
  "Screen"
 ],
 "CC Light Sweep-0003": [
  "Linear",
  "Smooth",
  "Sharp"
 ],
 "CC Light Sweep-0009": [
  "Add",
  "Composite",
  "Cutout"
 ],
 "CC Light Wipe-0004": [
  "Doors",
  "Round",
  "Square"
 ],
 "CC Mr. Mercury-0011": [
  "Explosive",
  "Fractal Explosive",
  "Twirl",
  "Twirly",
  "Vortex",
  "Fire",
  "(-",
  "Direction",
  "Direction Normalized",
  "Bi-Directional",
  "Bi-Directional Normalized",
  "(-",
  "Jet",
  "Jet Sideways"
 ],
 "CC Mr. Mercury-0013": [
  "Blob out",
  "Blob in",
  "Blob in & out",
  "Blob out sharp",
  "Constant Blobs"
 ],
 "CC Mr. Mercury-0031": [
  "Effect Light",
  "AE Lights"
 ],
 "CC Mr. Mercury-0019": [
  "Distant Light",
  "Point Light"
 ],
 "CC Mr. Smoothie-0002": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness",
  "Hue",
  "Saturation"
 ],
 "CC Mr. Smoothie-0007": [
  "AB",
  "BA",
  "ABA",
  "BAB"
 ],
 "CC Overbrights-0001": [
  "RGB Solid",
  "Lightness Solid",
  "Luminance Solid",
  "(-",
  "RGB Clip",
  "Lightness Clip",
  "Luminance Clip"
 ],
 "CC PS Classic-0009": [
  "Explosive",
  "Sideways",
  "Fire",
  "Bonfire",
  "Twirl",
  "Fountain",
  "Viscouse",
  "Scatterize",
  "Sparkle",
  "Vortexy",
  "(-",
  "Rain Drops",
  "Star Light",
  "Smokish",
  "Bubbly",
  "Bally",
  "Watery Drops",
  "Experimental"
 ],
 "CC PS LE Classic-0012": [
  "Explosive",
  "Sideways",
  "Fire",
  "Bonfire",
  "Twirl",
  "Fountain",
  "Viscouse",
  "Scatterize",
  "Sparkle",
  "Fractal Explosion",
  "Vortexy",
  "Jet",
  "Jet Sideways",
  "(-",
  "Star Light",
  "Bally",
  "Smokish",
  "Bubblish",
  "FireFly",
  "Watery Drops",
  "Experimental",
  "2Experimental"
 ],
 "CC Page Turn-0008": [
  "Classic UI",
  "(-",
  "Top Left Corner",
  "Top Right Corner",
  "Bottom Left Corner",
  "Bottom Right Corner"
 ],
 "CC Page Turn-0007": [
  "Front & Back Page",
  "Back Page",
  "Front Page"
 ],
 "CC Particle Systems II-0009": [
  "Explosive",
  "Fractal Explosive",
  "Twirl",
  "Twirly",
  "Vortex",
  "Fire",
  "(-",
  "Direction",
  "Direction Normalized",
  "(-",
  "Jet Sideways"
 ],
 "CC Particle Systems II-0018": [
  "Line",
  "Star",
  "(-",
  "Shaded Sphere",
  "Faded Sphere",
  "Shaded&Faded Sphere",
  "Bubble",
  "(-",
  "Motion Polygon",
  "TriPolygon",
  "QuadPolygon",
  "Cube",
  "TetraHedron",
  "Textured TriPolygon",
  "Textured QuadPolygon",
  "(-",
  "Lens Convex",
  "Lens Concave",
  "Lens Fade",
  "Lens Darken Fade",
  "Lens Bubble"
 ],
 "CC Particle Systems II-0022": [
  "Constant",
  "Fade Out Sharp",
  "Fade Out",
  "Fade In",
  "Fade In and Out",
  "Oscillate"
 ],
 "CC Particle Systems II-0024": [
  "Birth to Death",
  "Origin to Death",
  "Birth to Origin",
  "Origin Constant"
 ],
 "CC Particle Systems II-0028": [
  "Composite",
  "Screen",
  "Add",
  "Black Matte"
 ],
 "CC Particle World-0056": [
  "Floor",
  "Producer",
  "World"
 ],
 "CC Particle World-0057": [
  "X Axis",
  "Y Axis",
  "Z Axis"
 ],
 "CC Particle World-0015": [
  "Explosive",
  "Direction Axis",
  "Cone Axis",
  "(-",
  "Viscouse",
  "Twirl",
  "Twirly",
  "Vortex",
  "Fire",
  "(-",
  "Jet Sideways",
  "(-",
  "Fractal Omni",
  "Fractal Uni"
 ],
 "CC Particle World-0064": [
  "All",
  "Above Floor",
  "After Floor"
 ],
 "CC Particle World-0065": [
  "Normal",
  "Reflected on Floor",
  "Projected on Floor"
 ],
 "CC Particle World-0066": [
  "None",
  "Ice",
  "Glue",
  "Bounce"
 ],
 "CC Particle World-0023": [
  "Line",
  "Star",
  "(-",
  "Shaded Sphere",
  "Faded Sphere",
  "Darken&Faded Sphere",
  "Bubble",
  "(-",
  "Motion Polygon",
  "Motion Square",
  "TriPolygon",
  "QuadPolygon",
  "Textured TriPolygon",
  "Textured QuadPolygon",
  "Tetrahedron",
  "Cube",
  "(-",
  "Lens Convex",
  "Lens Concave",
  "Lens Fade",
  "Lens Darken Fade",
  "Lens Bubble",
  "(-",
  "Textured Square",
  "Textured Disc",
  "Textured Faded Disc"
 ],
 "CC Particle World-0047": [
  "Birth",
  "Current",
  "From Start"
 ],
 "CC Particle World-0071": [
  "X Axis",
  "Y Axis",
  "Z Axis",
  "Any Axis"
 ],
 "CC Particle World-0028": [
  "Custom",
  "Birth to Death",
  "Origin to Death",
  "Birth to Origin",
  "Origin Constant"
 ],
 "CC Particle World-0039": [
  "Composite",
  "Screen",
  "Add",
  "Black Matte"
 ],
 "CC Particle World-0082": [
  "None",
  "Fade",
  "Fog"
 ],
 "CC Pixel Polly-0008": [
  "Polygon",
  "Textured Polygon",
  "(-",
  "Square",
  "Textured Square"
 ],
 "CC Plastic-0003": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness"
 ],
 "CC Plastic-0026": [
  "Effect Light",
  "AE Lights"
 ],
 "CC Plastic-0012": [
  "Distant Light",
  "Point Light"
 ],
 "CC Radial Blur-0001": [
  "Straight Zoom",
  "Fading Zoom",
  "Centered Zoom",
  "(-",
  "Rotate",
  "Scratch",
  "Rotate Fading"
 ],
 "CC Radial Fast Blur-0003": [
  "Standard",
  "Brightest",
  "Darkest"
 ],
 "CC RepeTile-0005": [
  "Repeat",
  "Checker Flip H",
  "Checker Flip V",
  "Unfold",
  "Checker 180 deg",
  "Checker Flip 45 deg",
  "Checker 90 deg CCW",
  "Checker 90 deg CW",
  "Rosette",
  "Random",
  "None",
  "(-",
  "Turn CW",
  "Turn CCW",
  "Twist",
  "Slide",
  "Brick"
 ],
 "CC Scatterize-0004": [
  "Composite",
  "Screen",
  "Add",
  "Alpha Add"
 ],
 "CC Simple Wire Removal-0003": [
  "Fade",
  "Frame Offset",
  "Displace",
  "Displace Horizontal"
 ],
 "CC Smear-0005": [
  "Classic",
  "Round",
  "Bell",
  "Wizard"
 ],
 "CC Sphere-0026": [
  "XYZ",
  "XZY",
  "YXZ",
  "YZX",
  "ZXY",
  "ZYX"
 ],
 "CC Sphere-0008": [
  "Full",
  "Outside",
  "Inside"
 ],
 "CC Spotlight-0008": [
  "Light Only",
  "Light Add",
  "Light Add+",
  "Light Shadow",
  "(-",
  "Gel Only",
  "Gel Add",
  "Gel Add+",
  "Gel Shadow"
 ],
 "CC Threshold-0002": [
  "Luminance",
  "RGB",
  "Saturation",
  "Alpha"
 ],
 "CC Time Blend-0001": [
  "Blend",
  "Composite Over",
  "Composite Under",
  "Screen",
  "Add",
  "Soft Light",
  "Hard Light",
  "Lighten",
  "Darken",
  "Multiply",
  "Difference",
  "Color",
  "Overlay",
  "Luminosity",
  "(-",
  "Blend - Classic",
  "Composite Over - Classic",
  "Composite Under - Classic"
 ],
 "CC Time Blend-0003": [
  "Transparent",
  "Current Frame"
 ],
 "CC Time Blend FX-0001": [
  "Copy",
  "Paste"
 ],
 "CC Time Blend FX-0002": [
  "Blend",
  "Composite Over",
  "Composite Under",
  "Screen",
  "Add",
  "Soft Light",
  "Hard Light",
  "Lighten",
  "Darken",
  "Multiply",
  "Difference",
  "Color",
  "Overlay",
  "Luminosity",
  "(-",
  "Blend - Classic",
  "Composite Over - Classic",
  "Composite Under - Classic"
 ],
 "CC Time Blend FX-0004": [
  "Transparent",
  "Current Frame"
 ],
 "CC Toner-0005": [
  "Duotone",
  "Tritone",
  "Pentone",
  "(-",
  "Solid"
 ],
 "CC Vector Blur-0001": [
  "Natural",
  "Constant Length",
  "Perpendicular",
  "Direction Center",
  "Direction Fading"
 ],
 "CC Vector Blur-0006": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Lightness",
  "Hue",
  "Saturation"
 ],
 "CC WarpoMatic-0003": [
  "Brightness",
  "Contrast Differences",
  "Brightness Differences",
  "Local Differences"
 ],
 "CC WarpoMatic-0006": [
  "Joint",
  "Opposing",
  "Twisting"
 ],
 "CC Wide Time-0003": [
  "On",
  "Off"
 ],
 "ADBE 3D Glasses2-0008": [
  "Pixels",
  "% of Source"
 ],
 "ADBE 3D Glasses2-0005": [
  "Stereo Pair (Side by Side)",
  "Over Under",
  "Interlace Upper L Lower R",
  "Difference",
  "(-",
  "Red Green LR",
  "Red Blue LR",
  "(-",
  "Balanced Red Green LR",
  "Balanced Red Blue LR",
  "(-",
  "Balanced Colored Red Blue"
 ],
 "ADBE 3D Glasses-0008": [
  "Pixels",
  "% of Source"
 ],
 "ADBE 3D Glasses-0005": [
  "Stereo Pair (Side by Side)",
  "Interlace Upper L Lower R",
  "(-",
  "Red Green LR",
  "Red Blue LR",
  "(-",
  "Balanced Red Green LR",
  "Balanced Red Blue LR",
  "(-",
  "Balanced Colored Red Blue",
  "(-",
  "Over Under",
  "Difference"
 ],
 "ADBE Arithmetic-0001": [
  "And",
  "Or",
  "Xor",
  "Add",
  "Subtract",
  "Difference",
  "Min",
  "Max",
  "Block Above",
  "Block Below",
  "Slice",
  "Multiply",
  "Screen"
 ],
 "ADBE AudSpect-0020": [
  "Digital",
  "Analog lines",
  "Analog dots"
 ],
 "ADBE AudSpect-0021": [
  "Side A",
  "Side B",
  "Side A & B"
 ],
 "ADBE AudWave-0014": [
  "Mono",
  "Left",
  "Right"
 ],
 "ADBE AudWave-0015": [
  "Digital",
  "Analog lines",
  "Analog dots"
 ],
 "ADBE Aud Distortion-0008": [
  "Soft Clip",
  "Hard Clip",
  "Saturation 1",
  "Saturation 2",
  "Tube",
  "Fuzz"
 ],
 "ADBE Aud HiLo-0001": [
  "High Pass",
  "Low Pass"
 ],
 "ADBE Aud Modulator-0001": [
  "Sine",
  "Triangle"
 ],
 "ADBE Aud Tone-0001": [
  "Sine",
  "Triangle",
  "Saw",
  "Square",
  "White Noise"
 ],
 "ADBE AUX CHANNEL EXTRACT-0001": [
  "Z-Depth",
  "Object ID",
  "Texture UV",
  "Surface Normals",
  "Coverage",
  "Background RGB",
  "Unclamped RGB",
  "Material ID"
 ],
 "ADBE Basic Text2-0007": [
  "Fill Only",
  "Stroke Only",
  "Fill Over Stroke",
  "Stroke Over Fill"
 ],
 "ADBE Blend-0002": [
  "Crossfade",
  "Color Only",
  "Tint Only",
  "Darken Only",
  "Lighten Only"
 ],
 "ADBE Blend-0004": [
  "Center",
  "Stretch to Fit"
 ],
 "ADBE Box Blur2-0003": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Box Blur-0003": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Broadcast Colors-0001": [
  "NTSC",
  "PAL"
 ],
 "ADBE Broadcast Colors-0002": [
  "Reduce Luminance",
  "Reduce Saturation",
  "(-",
  "Key Out Unsafe",
  "Key Out Safe"
 ],
 "ADBE Brush Strokes-0006": [
  "Paint On Original Image",
  "Paint On Transparent",
  "Paint On White",
  "Paint On Black"
 ],
 "ADBE Bulge-0006": [
  "Low",
  "High"
 ],
 "ADBE Calculations-0002": [
  "RGBA",
  "Gray",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Calculations-0007": [
  "RGBA",
  "Gray",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Calculations-0012": [
  "Normal",
  "Copy",
  "(-",
  "Darken",
  "Multiply",
  "Color Burn",
  "Classic Color Burn",
  "(-",
  "Add",
  "Lighten",
  "Screen",
  "Color Dodge",
  "Classic Color Dodge",
  "(-",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "Linear Light",
  "Vivid Light",
  "Pin Light",
  "(-",
  "Difference",
  "Classic Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity",
  "(-",
  "Stencil Alpha",
  "Stencil Luma",
  "Silhouette Alpha",
  "Silhouette Luma",
  "(-",
  "Alpha Add",
  "Luminescent Add"
 ],
 "ADBE WRPMESH-0001": [
  "Arc",
  "Arc Lower",
  "Arc Upper",
  "Arch",
  "Bulge",
  "Shell Lower",
  "Shell Upper",
  "Flag",
  "Wave",
  "Fish",
  "Rise",
  "FishEye",
  "Inflate",
  "Twist",
  "Squeeze"
 ],
 "ADBE WRPMESH-0002": [
  "Horizontal",
  "Vertical"
 ],
 "APC CardDanceCam-0002": [
  "Independent",
  "Columns Follows Rows"
 ],
 "APC CardDanceCam-0014": [
  "XYZ",
  "XZY",
  "YXZ",
  "YZX",
  "ZXY",
  "ZYX"
 ],
 "APC CardDanceCam-0016": [
  "Position, Rotate, Scale",
  "Position, Scale, Rotate",
  "Rotate, Position, Scale",
  "Rotate, Scale, Position",
  "Scale, Position, Rotate",
  "Scale, Rotate, Position"
 ],
 "APC CardDanceCam-0018": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0024": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0030": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0036": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0042": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0048": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0054": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0060": [
  "None",
  "Intensity 1",
  "Red 1",
  "Green 1",
  "Blue 1",
  "Alpha 1",
  "Intensity H Slope 1",
  "Intensity V Slope 1",
  "Red H Slope 1",
  "Red V Slope 1",
  "Intensity 2",
  "Red 2",
  "Green 2",
  "Blue 2",
  "Alpha 2",
  "Intensity H Slope 2",
  "Intensity V Slope 2",
  "Red H Slope 2",
  "Red V Slope 2"
 ],
 "APC CardDanceCam-0066": [
  "Camera Position",
  "Corner Pins",
  "Comp Camera"
 ],
 "APC CardDanceCam-0080": [
  "Rotate XYZ, Position",
  "Rotate XZY, Position",
  "Rotate YXZ, Position",
  "Rotate YZX, Position",
  "Rotate ZXY, Position",
  "Rotate ZYX, Position",
  "Position, Rotate XYZ",
  "Position, Rotate XZY",
  "Position, Rotate YXZ",
  "Position, Rotate YZX",
  "Position, Rotate ZXY",
  "Position, Rotate ZYX"
 ],
 "APC CardDanceCam-0102": [
  "Point Source",
  "Distant Source",
  "First Comp Light"
 ],
 "APC CardWipeCam-0008": [
  "Independent",
  "Columns Follows Rows"
 ],
 "APC CardWipeCam-0016": [
  "X",
  "Y",
  "Random"
 ],
 "APC CardWipeCam-0018": [
  "Positive",
  "Negative",
  "Random"
 ],
 "APC CardWipeCam-0020": [
  "Left to Right",
  "Right to Left",
  "Top to Bottom",
  "Bottom to Top",
  "Top Left to Bottom Right",
  "Top Right to Bottom Left",
  "Bottom Left to Top Right",
  "Bottom Right to Top Left",
  "Gradient"
 ],
 "APC CardWipeCam-0028": [
  "Camera Position",
  "Corner Pins",
  "Comp Camera"
 ],
 "APC CardWipeCam-0042": [
  "Rotate XYZ, Position",
  "Rotate XZY, Position",
  "Rotate YXZ, Position",
  "Rotate YZX, Position",
  "Rotate ZXY, Position",
  "Rotate ZYX, Position",
  "Position, Rotate XYZ",
  "Position, Rotate XZY",
  "Position, Rotate YXZ",
  "Position, Rotate YZX",
  "Position, Rotate ZXY",
  "Position, Rotate ZYX"
 ],
 "APC CardWipeCam-0064": [
  "Point Source",
  "Distant Source",
  "First Comp Light"
 ],
 "ADBE Cartoonify-0001": [
  "Fill",
  "Edges",
  "Fill & Edges"
 ],
 "APC Caustics-0006": [
  "Once",
  "Tiled",
  "Reflected"
 ],
 "APC Caustics-0008": [
  "Center",
  "Stretch to Fit"
 ],
 "APC Caustics-0074": [
  "Once",
  "Tiled",
  "Reflected"
 ],
 "APC Caustics-0076": [
  "Center",
  "Stretch to Fit"
 ],
 "APC Caustics-0038": [
  "Point Source",
  "Distant Source",
  "First Comp Light"
 ],
 "ADBE Cell Pattern-0001": [
  "Bubbles",
  "Crystals",
  "Plates",
  "Static Plates",
  "Crystallize",
  "(-",
  "Pillow",
  "Crystals HQ",
  "Plates HQ",
  "Static Plates HQ",
  "Crystallize HQ",
  "Mixed Crystals",
  "Tubular"
 ],
 "ADBE Cell Pattern-0004": [
  "Clip",
  "Soft Clamp",
  "Wrap Back"
 ],
 "ADBE Change To Color-0003": [
  "Hue",
  "Hue & Lightness",
  "Hue & Saturation",
  "Hue, Lightness & Saturation"
 ],
 "ADBE Change To Color-0004": [
  "Setting To Color",
  "Transforming To Color"
 ],
 "ADBE Change Color-0001": [
  "Corrected Layer",
  "Color Correction Mask"
 ],
 "ADBE Change Color-0008": [
  "Using RGB",
  "Using Hue",
  "Using Chroma"
 ],
 "ADBE Channel Combiner-0005": [
  "RGB to HLS",
  "HLS to RGB",
  "RGB to YUV",
  "YUV to RGB",
  "Straight to Premultiplied",
  "(-",
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "(-",
  "Hue",
  "Lightness",
  "Luminance",
  "Saturation",
  "Saturation Multiplied",
  "(-",
  "Min RGB",
  "Max RGB"
 ],
 "ADBE Channel Combiner-0006": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "(-",
  "Hue",
  "Lightness",
  "Saturation",
  "(-",
  "Red only",
  "Green only",
  "Blue only",
  "Alpha only",
  "(-",
  "Hue only",
  "Lightness only",
  "Saturation only"
 ],
 "ADBE Channel Blur-0006": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Checkerboard-0002": [
  "Corner Point",
  "Width Slider",
  "Width & Height Sliders"
 ],
 "ADBE Checkerboard-0012": [
  "None",
  "Normal",
  "Stencil Alpha",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Cineon Converter-0001": [
  "Log to Linear (obsolete)",
  "Linear to Log",
  "Log to Linear",
  "Log to Log",
  "Log to Linear (obsolete)",
  "Log to Log (obsolete)"
 ],
 "ADBE Cineon Converter2-0001": [
  "Linear to Log",
  "Log to Linear",
  "Log to Log"
 ],
 "ADBE Circle-0003": [
  "None",
  "Edge Radius",
  "Thickness",
  "Thickness * Radius",
  "Thickness & Feather * Radius"
 ],
 "ADBE Circle-0012": [
  "None",
  "Normal",
  "Stencil Alpha",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Color Link-0002": [
  "Average",
  "Median",
  "Brightest",
  "Darkest",
  "Max RGB",
  "Min RGB",
  "(-",
  "Average Alpha",
  "Median Alpha",
  "Max Alpha",
  "Min Alpha"
 ],
 "ADBE Color Link-0005": [
  "Normal",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Color Difference Key-0002": [
  "Source",
  "Matte Partial A Uncorrected",
  "Matte Partial A Corrected",
  "Matte Partial B Uncorrected",
  "Matte Partial B Corrected",
  "Matte Uncorrected",
  "Matte Corrected",
  "Final Output",
  "(-",
  "[A, B, Matte] Corrected, Final"
 ],
 "ADBE Color Difference Key-0004": [
  "Faster",
  "More Accurate"
 ],
 "ADBE Color Range-0003": [
  "Lab",
  "YUV",
  "RGB"
 ],
 "APC Colorama-0002": [
  "Intensity",
  "Red",
  "Green",
  "Blue",
  "Hue",
  "Lightness",
  "Saturation",
  "Value",
  "Alpha",
  "Zero"
 ],
 "APC Colorama-0006": [
  "Intensity",
  "Red",
  "Green",
  "Blue",
  "Hue",
  "Lightness",
  "Saturation",
  "Value",
  "Alpha",
  "Zero"
 ],
 "APC Colorama-0040": [
  "Wrap",
  "Clamp",
  "Average",
  "Screen"
 ],
 "APC Colorama-0010": [
  "[none]",
  "Alpha Ramp",
  "Hue Cycle",
  "Negative",
  "Ramp Red",
  "Ramp Green",
  "Ramp Blue",
  "Ramp Grey",
  "RGB",
  "Saturation Ramp",
  "Solarize Red",
  "Solarize Green",
  "Solarize Blue",
  "Solarize Grey",
  "(-",
  "Carribean",
  "Clay",
  "Copper",
  "Deep Ocean",
  "Earthenware",
  "Fire",
  "Fire And Smoke",
  "Golden 1",
  "Golden 2",
  "Granite",
  "Horizon",
  "Leather",
  "Moldy",
  "Mossy",
  "Old Glory",
  "Rusty",
  "Sepia 1",
  "Sepia 2",
  "Skink",
  "Sunset"
 ],
 "APC Colorama-0016": [
  "All",
  "Red",
  "Green",
  "Blue",
  "RG",
  "GB",
  "RB",
  "Hue",
  "Lightness",
  "Saturation",
  "HL",
  "LS",
  "HS",
  "None"
 ],
 "APC Colorama-0026": [
  "Off",
  "RGB",
  "Hue",
  "Chroma"
 ],
 "APC Colorama-0030": [
  "Off",
  "Intensity",
  "Alpha",
  "Inverted Intensity",
  "Inverted Alpha"
 ],
 "ADBE 4ColorGradient-0014": [
  "None",
  "Normal",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Compound Arithmetic-0002": [
  "Copy",
  "Add",
  "Subtract",
  "Multiply",
  "Difference",
  "And",
  "Or",
  "Xor",
  "Lighter",
  "Darker",
  "Minimum",
  "Maximum",
  "Screen",
  "Overlay",
  "Hard Light"
 ],
 "ADBE Compound Arithmetic-0003": [
  "RGB",
  "ARGB",
  "Alpha"
 ],
 "ADBE Compound Arithmetic-0004": [
  "Clip",
  "Wrap",
  "Scale"
 ],
 "ADBE CurvesCustom-0002": [
  "RGB",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE CameraShakeDeblur-0002": [
  "Standard",
  "High Quality (slower)"
 ],
 "ADBE Deflicker-0001": [
  "Brightness",
  "Levels",
  "Curves"
 ],
 "ADBE Difference Matte2-0001": [
  "Final Output",
  "Source Only",
  "Matte Only"
 ],
 "ADBE Difference Matte2-0003": [
  "Center",
  "Stretch to Fit"
 ],
 "ADBE Difference-0005": [
  "Original",
  "Target",
  "Blend",
  "Max",
  "Full On",
  "(-",
  "Lightness of Result",
  "Max of Result",
  "(-",
  "Alpha Difference",
  "Alpha Difference Only"
 ],
 "ADBE Displacement Map-0002": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Half",
  "Off"
 ],
 "ADBE Displacement Map-0004": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Half",
  "Off"
 ],
 "ADBE Displacement Map-0006": [
  "Center Map",
  "Stretch Map to Fit",
  "Tile Map"
 ],
 "ADBE Echo-0005": [
  "Add",
  "Maximum",
  "Minimum",
  "Screen",
  "Composite In Back",
  "Composite In Front",
  "Blend"
 ],
 "ADBE Equalize-0001": [
  "RGB",
  "Brightness",
  "Photoshop Style"
 ],
 "ADBE Compander-0001": [
  "Compress Range",
  "Expand Range"
 ],
 "ADBE Exposure2-0001": [
  "Master",
  "Individual Channels"
 ],
 "ADBE Exposure-0001": [
  "Master",
  "Individual Channels"
 ],
 "ADBE Extract-0002": [
  "Luminance",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Eyedropper Fill-0003": [
  "Skip Empty",
  "All",
  "All Premultiplied",
  "Including Alpha"
 ],
 "ADBE Fast Blur-0002": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "APC Foam-0002": [
  "Draft",
  "Draft + Flow Map",
  "Rendered"
 ],
 "APC Foam-0050": [
  "Transparent",
  "Solid Old on top",
  "Solid New on top"
 ],
 "APC Foam-0052": [
  "User Defined",
  "-",
  "Default Bubble",
  "Amber Bock",
  "Water Beads",
  "Spit",
  "Cartoon Coffee",
  "Winter Stream",
  "Soda Water",
  "Orange Soda",
  "Nuclear Waste",
  "Red Tide",
  "Magma Marbles",
  "Sunset Foam",
  "Pepto",
  "Algae",
  "Blisters",
  "Bubble Wrap",
  "Grape Soda"
 ],
 "APC Foam-0056": [
  "Fixed",
  "Physical Orientation",
  "Bubble Velocity"
 ],
 "APC Foam-0068": [
  "Universe",
  "Screen"
 ],
 "APC Foam-0070": [
  "Normal",
  "High",
  "Intense"
 ],
 "ADBE Fractal-0002": [
  "Mandelbrot",
  "Mandelbrot Inverse",
  "Mandelbrot over Julia",
  "Mandelbrot Inverse over Julia",
  "Julia",
  "Julia Inverse"
 ],
 "ADBE Fractal-0032": [
  "z = z^2 + c",
  "z = z^3 + c",
  "z = z^5 + c",
  "z = z^7 + c"
 ],
 "ADBE Fractal-0018": [
  "Lightness Gradient",
  "Hue Wheel",
  "Black And White",
  "Solid Color",
  "Escape Angle",
  "Grayscale",
  "Apple ]["
 ],
 "ADBE Fractal-0025": [
  "Edge Detect-Fast-May miss pixels",
  "Brute Force-Slow-Every pixel"
 ],
 "ADBE Fractal Noise-0001": [
  "Basic",
  "(-",
  "Turbulent Smooth",
  "Turbulent Basic",
  "Turbulent Sharp",
  "(-",
  "Dynamic",
  "Dynamic Progressive",
  "Dynamic Twist",
  "(-",
  "Max",
  "Smeary",
  "Swirly",
  "Rocky",
  "Cloudy",
  "Terrain",
  "Subscale",
  "Small Bumps",
  "Strings",
  "Threads"
 ],
 "ADBE Fractal Noise-0002": [
  "Block",
  "Linear",
  "Soft Linear",
  "Spline"
 ],
 "ADBE Fractal Noise-0006": [
  "Clip",
  "Soft Clamp",
  "Wrap Back",
  "Allow HDR Results"
 ],
 "ADBE Fractal Noise-0030": [
  "None",
  "Normal",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Luminosity"
 ],
 "ADBE Gaussian Blur-0002": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Gaussian Blur 2-0002": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Glo2-0001": [
  "Alpha Channel",
  "Color Channels"
 ],
 "ADBE Glo2-0005": [
  "On Top",
  "Behind",
  "None"
 ],
 "ADBE Glo2-0006": [
  "None",
  "Normal",
  "Add",
  "Multiply",
  "Dissolve",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "Darken",
  "Lighten",
  "Difference",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity",
  "Color Dodge",
  "Color Burn",
  "Exclusion",
  "Stencil Alpha",
  "Stencil Luma",
  "Silhouette Alpha",
  "Silhouette Luma",
  "Luminescent Premultiply",
  "Alpha Add"
 ],
 "ADBE Glo2-0007": [
  "Original Colors",
  "A & B Colors",
  "Arbitrary Map"
 ],
 "ADBE Glo2-0008": [
  "Sawtooth A>B",
  "Sawtooth B>A",
  "Triangle A>B>A",
  "Triangle B>A>B"
 ],
 "ADBE Glo2-0014": [
  "Horizontal and Vertical",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Gradient Wipe-0004": [
  "Tile Gradient",
  "Center Gradient",
  "Stretch Gradient to Fit"
 ],
 "ADBE Grid-0002": [
  "Corner Point",
  "Width Slider",
  "Width & Height Sliders"
 ],
 "ADBE Grid-0014": [
  "None",
  "Normal",
  "Stencil Alpha",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE HUE SATURATION-0002": [
  "Master",
  "Reds",
  "Yellows",
  "Greens",
  "Cyans",
  "Blues",
  "Magentas"
 ],
 "ADBE ID MATTE-0001": [
  "Material ID",
  "Object ID"
 ],
 "ADBE Invert-0001": [
  "RGB",
  "Red",
  "Green",
  "Blue",
  "(-",
  "HLS",
  "Hue",
  "Lightness",
  "Saturation",
  "(-",
  "YIQ",
  "Luminance",
  "In Phase Chrominance",
  "Quadrature Chrominance",
  "(-",
  "Alpha"
 ],
 "ADBE Leave Color-0005": [
  "Using RGB",
  "Using Hue"
 ],
 "ADBE Easy Levels-0001": [
  "RGB",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Easy Levels2-0001": [
  "RGB",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Easy Levels2-0008": [
  "On",
  "Off",
  "Off for 32 bpc Color"
 ],
 "ADBE Easy Levels2-0009": [
  "On",
  "Off",
  "Off for 32 bpc Color"
 ],
 "ADBE Pro Levels2-0001": [
  "RGB",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Pro Levels2-0038": [
  "On",
  "Off",
  "Off for 32 bpc Color"
 ],
 "ADBE Pro Levels2-0039": [
  "On",
  "Off",
  "Off for 32 bpc Color"
 ],
 "ADBE Pro Levels-0001": [
  "RGB",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Lightning-0024": [
  "Normal",
  "Add",
  "Screen"
 ],
 "ADBE Lightning 2-0001": [
  "Direction",
  "Strike",
  "Breaking",
  "Bouncey",
  "(-",
  "Omni",
  "Anywhere",
  "Vertical",
  "Two-Way Strike"
 ],
 "ADBE Lightning 2-0026": [
  "Linear",
  "Semi Linear",
  "Spline"
 ],
 "ADBE Linear Color Key2-0002": [
  "Final Output",
  "Source Only",
  "Matte Only"
 ],
 "ADBE Linear Color Key2-0004": [
  "Using RGB",
  "Using Hue",
  "Using Chroma"
 ],
 "ADBE Linear Color Key2-0007": [
  "Key Colors",
  "Keep Colors"
 ],
 "ADBE LIQUIFY-0006": [
  "Revert",
  "Displace",
  "Amplitwist",
  "Affine"
 ],
 "ADBE LIQUIFY-0011": [
  "Small",
  "Medium",
  "Large"
 ],
 "ADBE LIQUIFY-0012": [
  "Red",
  "Yellow",
  "Green",
  "Cyan",
  "Blue",
  "Magenta",
  "Gray"
 ],
 "ADBE Luma Key-0001": [
  "Key Out Brighter",
  "Key Out Darker",
  "Key Out Similar",
  "Key Out Dissimilar"
 ],
 "ADBE Lumetri-0005": [
  "None",
  "[Custom]",
  "Browse..."
 ],
 "ADBE Lumetri-0127": [
  "None",
  "[Custom]",
  "Browse...",
  "(-",
  "ALEXA_Default_LogC2Rec709",
  "AlexaV3_K1S1_LogC2Video_DCIP3_EE",
  "AlexaV3_K1S1_LogC2Video_Rec709_EE",
  "AMIRA_Default_LogC2Rec709",
  "ARRI_Universal_DCI",
  "ARRI_Universal_HD",
  "D-21_delogC_EI0200_B1",
  "Phantom_Rec709_Gamma"
 ],
 "ADBE Lumetri-0025": [
  "None",
  "[Custom]",
  "Browse..."
 ],
 "ADBE Lumetri-0128": [
  "None",
  "[Custom]",
  "Browse...",
  "(-",
  "CineSpace2383sRGB6bit",
  "Fuji ETERNA 250D Fuji 3510 (by Adobe)",
  "Fuji ETERNA 250D Kodak 2395 (by Adobe)",
  "Fuji F125 Kodak 2393 (by Adobe)",
  "Fuji F125 Kodak 2395 (by Adobe)",
  "Fuji REALA 500D Kodak 2393 (by Adobe)",
  "Kodak 5205 Fuji 3510 (by Adobe)",
  "Kodak 5218 Kodak 2383 (by Adobe)",
  "Kodak 5218 Kodak 2395 (by Adobe)",
  "Monochrome Fuji ETERNA 250D Kodak 2395 (by Adobe)",
  "Monochrome Kodak 5205 Fuji 3510 (by Adobe)",
  "Monochrome Kodak 5218 Kodak 2395 (by Adobe)",
  "SL BIG",
  "SL BIG HDR",
  "SL BIG LDR",
  "SL BIG MINUS BLUE",
  "SL BLEACH HDR",
  "SL BLEACH LDR",
  "SL BLEACH NDR",
  "SL BLUE COLD",
  "SL BLUE DAY4NITE",
  "SL BLUE ICE",
  "SL BLUE INTENSE",
  "SL BLUE MOON",
  "SL BLUE STEEL",
  "SL CLEAN FUJI A HDR",
  "SL CLEAN FUJI A LDR",
  "SL CLEAN FUJI A NDR",
  "SL CLEAN FUJI B",
  "SL CLEAN FUJI B SOFT",
  "SL CLEAN FUJI C",
  "SL CLEAN KODAK A HDR",
  "SL CLEAN KODAK A LDR",
  "SL CLEAN KODAK A NDR",
  "SL CLEAN KODAK B",
  "SL CLEAN KODAK B SOFT",
  "SL CLEAN KODAK B ULTRASOFT",
  "SL CLEAN KODAK C",
  "SL CLEAN KODAK C HDR",
  "SL CLEAN STRAIGHT HDR",
  "SL CLEAN STRAIGHT LDR",
  "SL CLEAN STRAIGHT NDR",
  "SL CROSS HDR",
  "SL CROSS LDR",
  "SL CROSS NDR",
  "SL GOLD HEAT",
  "SL GOLD ORANGE",
  "SL GOLD RUSH HDR",
  "SL GOLD RUSH LDR",
  "SL GOLD TOBACCO",
  "SL GOLD WESTERN",
  "SL IRON HDR",
  "SL IRON LDR",
  "SL IRON NDR",
  "SL MATRIX BLUE",
  "SL MATRIX GREEN",
  "SL MATRIX MARS",
  "SL NEUTRAL START",
  "SL NOIR 1965",
  "SL NOIR HDR"
 ],
 "ADBE Lumetri-0130": [
  "None",
  "ACEScct",
  "Apple Log/Rec. 2020",
  "ARRI LogC3/Wide Gamut3",
  "ARRI LogC4/Wide Gamut4",
  "Canon Log/Cinema Gamut",
  "Canon Log2/Cinema Gamut",
  "Canon Log3/Cinema Gamut",
  "DCDM X'Y'Z'",
  "DJI D-Log/D-Gamut",
  "Fuji F-Log/Rec. 2020",
  "Fuji F-Log2/Rec. 2020",
  "Leica L-Log/Rec. 2020",
  "Nikon N-Log/Rec2020",
  "P3-D65 HLG",
  "P3-D65 PQ",
  "Panasonic V-Log/V-Gamut",
  "Rec. 2020",
  "Rec. 2020 (Scene)",
  "Rec. 2100 HLG",
  "Rec. 2100 HLG (Scene)",
  "Rec. 2100 PQ",
  "Rec. 2100 PQ (Scene)",
  "Rec. 601 (NTSC)",
  "Rec. 601 (PAL)",
  "Rec. 709",
  "Rec. 709 (Scene)",
  "Red Log3G10/Wide Gamut",
  "Sony S-Log/S-Gamut",
  "Sony S-Log2/S-Gamut",
  "Sony S-Log3/S-Gamut3",
  "Sony S-Log3/S-Gamut3.Cine",
  "sRGB"
 ],
 "ADBE Lumetri-0075": [
  "Color/Gray",
  "Color/Black",
  "White/Black"
 ],
 "ADBE Magnify-0010": [
  "Circle",
  "Square"
 ],
 "ADBE Magnify-0011": [
  "None",
  "Size To Magnification",
  "Size & Feather To Magnification"
 ],
 "ADBE Magnify-0008": [
  "Standard",
  "Soft",
  "Scatter"
 ],
 "ADBE Magnify-0012": [
  "None",
  "Normal",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Minimax-0001": [
  "Minimum",
  "Maximum",
  "Minimum Then Maximum",
  "Maximum Then Minimum"
 ],
 "ADBE Minimax-0003": [
  "Color",
  "Alpha and Color",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Minimax-0004": [
  "Horizontal & Vertical",
  "Just Horizontal",
  "Just Vertical"
 ],
 "ADBE Noise Alpha2-0001": [
  "Uniform Random",
  "Squared Random",
  "(-",
  "Uniform Animation",
  "Squared Animation"
 ],
 "ADBE Noise Alpha2-0003": [
  "Add",
  "Clamp",
  "Scale",
  "Edges"
 ],
 "ADBE Noise Alpha2-0004": [
  "Clip",
  "Wrap Back",
  "Wrap"
 ],
 "ADBE Noise Alpha-0001": [
  "Uniform Random",
  "Squared Random",
  "(-",
  "Uniform Animation",
  "Squared Animation"
 ],
 "ADBE Noise Alpha-0003": [
  "Add",
  "Clamp",
  "Scale",
  "Edges"
 ],
 "ADBE Noise Alpha-0004": [
  "Clip",
  "Wrap Back",
  "Wrap"
 ],
 "ADBE Noise HLS-0001": [
  "Uniform",
  "Squared",
  "Grain"
 ],
 "ADBE Noise HLS2-0001": [
  "Uniform",
  "Squared",
  "Grain"
 ],
 "ADBE Noise HLS Auto2-0001": [
  "Uniform",
  "Squared",
  "Grain"
 ],
 "ADBE Noise HLS Auto-0001": [
  "Uniform",
  "Squared",
  "Grain"
 ],
 "ADBE Numbers2-0001": [
  "Number",
  "Number [Leading Zeros]",
  "Timecode [30]",
  "Timecode [25]",
  "Timecode [24]",
  "Time",
  "Numerical Date",
  "Short Date",
  "Long Date",
  "Hexadecimal"
 ],
 "ADBE Numbers2-0012": [
  "Fill Only",
  "Stroke Only",
  "Fill Over Stroke",
  "Stroke Over Fill"
 ],
 "ADBE Optics Compensation-0003": [
  "Horizontal",
  "Vertical",
  "Diagonal"
 ],
 "ADBE Optics Compensation-0006": [
  "Off",
  "Max 2X",
  "Max 4X",
  "Unlimited"
 ],
 "ADBE PhotoFilterPS-0001": [
  "Warming Filter (85)",
  "Warming Filter (LBA)",
  "Warming Filter (81)",
  "Cooling Filter (80)",
  "Cooling Filter (LBB)",
  "Cooling Filter (82)",
  "Red",
  "Orange",
  "Yellow",
  "Green",
  "Cyan",
  "Blue ",
  "Violet",
  "Magenta",
  "Sepia",
  "Deep Red",
  "Deep Blue",
  "Deep Emerald",
  "Deep Yellow",
  "Underwater",
  "(-",
  "Custom"
 ],
 "ADBE SelectiveColor-0001": [
  "Relative",
  "Absolute"
 ],
 "ADBE SelectiveColor-0002": [
  "Reds",
  "Yellows",
  "Greens",
  "Cyans",
  "Blues",
  "Magentas",
  "Whites",
  "Neutrals",
  "Blacks"
 ],
 "ADBE PSL Bevel Emboss-0005": [
  "Up",
  "Down"
 ],
 "ADBE PSL Bevel Emboss-0006": [
  "Emboss",
  "Pillow Emboss"
 ],
 "ADBE PSL Bevel Emboss-0007": [
  "Highlight",
  "Shadow"
 ],
 "ADBE PSL Inner Glow-0004": [
  "Center",
  "Edge"
 ],
 "ADBE Paint Bucket-0004": [
  "Color & Alpha",
  "Straight Color",
  "(-",
  "Transparency",
  "Opacity",
  "Alpha Channel"
 ],
 "ADBE Paint Bucket-0008": [
  "Antialias",
  "Feather",
  "Spread",
  "Choke",
  "Stroke"
 ],
 "ADBE Paint Bucket-0011": [
  "Fill Only",
  "Normal",
  "Stencil Alpha",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Playgnd-0252": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0254": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0284": [
  "Relative",
  "Absolute",
  "Relative Random",
  "Absolute Random"
 ],
 "ADBE Playgnd-0302": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0304": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0352": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0354": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0402": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0404": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0422": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0424": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0472": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0474": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0517": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0519": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0502": [
  "None",
  "Red",
  "Green",
  "Blue",
  "Kinetic Friction",
  "Static Friction",
  "Angle",
  "Angular Velocity",
  "Torque",
  "Scale",
  "X Scale",
  "Y Scale",
  "X",
  "Y",
  "Gradient Velocity",
  "X Speed",
  "Y Speed",
  "Gradient Force",
  "X Force",
  "Y Force",
  "Opacity",
  "Mass",
  "Lifespan",
  "Character",
  "Font Size",
  "Time Offset",
  "Scale Speed"
 ],
 "ADBE Playgnd-0506": [
  "None",
  "Red",
  "Green",
  "Blue",
  "Kinetic Friction",
  "Static Friction",
  "Angle",
  "Angular Velocity",
  "Torque",
  "Scale",
  "X Scale",
  "Y Scale",
  "X",
  "Y",
  "Gradient Velocity",
  "X Speed",
  "Y Speed",
  "Gradient Force",
  "X Force",
  "Y Force",
  "Opacity",
  "Mass",
  "Lifespan",
  "Character",
  "Font Size",
  "Time Offset",
  "Scale Speed"
 ],
 "ADBE Playgnd-0510": [
  "None",
  "Red",
  "Green",
  "Blue",
  "Kinetic Friction",
  "Static Friction",
  "Angle",
  "Angular Velocity",
  "Torque",
  "Scale",
  "X Scale",
  "Y Scale",
  "X",
  "Y",
  "Gradient Velocity",
  "X Speed",
  "Y Speed",
  "Gradient Force",
  "X Force",
  "Y Force",
  "Opacity",
  "Mass",
  "Lifespan",
  "Character",
  "Font Size",
  "Time Offset",
  "Scale Speed"
 ],
 "ADBE Playgnd-0567": [
  "All",
  "None",
  "Cannon",
  "Grid",
  "Layer Exploder",
  "Particle Exploder",
  "Cannon or Grid",
  "Cannon or Layer Exploder",
  "Cannon or Particle Exploder",
  "Grid or Layer Exploder",
  "Grid or Particle Exploder",
  "Layer Exploder or Particle Exploder",
  "Cannon or Grid or Layer Exploder",
  "Cannon or Grid or Particle Exploder",
  "Cannon or Layer Exploder or Particle Exploder",
  "Grid or Layer Exploder or Particle Exploder"
 ],
 "ADBE Playgnd-0569": [
  "None",
  "Selection Text 1",
  "Selection Text 2",
  "Selection Text 3"
 ],
 "ADBE Playgnd-0552": [
  "None",
  "Red",
  "Green",
  "Blue",
  "Angle",
  "Angular Velocity",
  "Scale",
  "X Scale",
  "Y Scale",
  "X",
  "Y",
  "Gradient Velocity",
  "X Speed",
  "Y Speed",
  "Opacity",
  "Character",
  "Font Size",
  "Time Offset",
  "Scale Speed"
 ],
 "ADBE Playgnd-0553": [
  "Set",
  "Add",
  "Difference",
  "Subtract",
  "Multiply",
  "Min",
  "Max"
 ],
 "ADBE Playgnd-0556": [
  "None",
  "Red",
  "Green",
  "Blue",
  "Angle",
  "Angular Velocity",
  "Scale",
  "X Scale",
  "Y Scale",
  "X",
  "Y",
  "Gradient Velocity",
  "X Speed",
  "Y Speed",
  "Opacity",
  "Character",
  "Font Size",
  "Time Offset",
  "Scale Speed"
 ],
 "ADBE Playgnd-0557": [
  "Set",
  "Add",
  "Difference",
  "Subtract",
  "Multiply",
  "Min",
  "Max"
 ],
 "ADBE Playgnd-0560": [
  "None",
  "Red",
  "Green",
  "Blue",
  "Angle",
  "Angular Velocity",
  "Scale",
  "X Scale",
  "Y Scale",
  "X",
  "Y",
  "Gradient Velocity",
  "X Speed",
  "Y Speed",
  "Opacity",
  "Character",
  "Font Size",
  "Time Offset",
  "Scale Speed"
 ],
 "ADBE Playgnd-0561": [
  "Set",
  "Add",
  "Difference",
  "Subtract",
  "Multiply",
  "Min",
  "Max"
 ],
 "ADBE Path Text-0021": [
  "Bezier",
  "Circle",
  "Loop",
  "Line"
 ],
 "ADBE Path Text-0036": [
  "Fill Only",
  "Stroke Only",
  "Fill Over Stroke",
  "Stroke Over Fill"
 ],
 "ADBE Path Text-0002": [
  "Left",
  "Right",
  "Center",
  "Force"
 ],
 "ADBE Path Text-0014": [
  "Normal",
  "Difference"
 ],
 "ADBE Photo Filter-0001": [
  "Warming Filter (85)",
  "Warming Filter (81)",
  "Cooling Filter (80)",
  "Cooling Filter (82)",
  "Red",
  "Orange",
  "Yellow",
  "Green",
  "Cyan",
  "Blue ",
  "Violet",
  "Magenta",
  "Sepia",
  "Deep Red",
  "Deep Blue",
  "Deep Emerald",
  "Deep Yellow",
  "Underwater",
  "(-",
  "Custom"
 ],
 "ADBE Polar Coordinates-0002": [
  "Rect to Polar",
  "Polar to Rect"
 ],
 "ADBE ProfileToProfile-0001": [
  "Project Working Space",
  "(-",
  "Adobe RGB (1998)",
  "Apple RGB",
  "ColorMatch RGB",
  "image P3",
  "ProPhoto RGB",
  "sRGB IEC61966-2.1",
  "(-",
  "Fujifilm ETERNA 250 Printing Density (by Adobe)",
  "Fujifilm ETERNA 250D Printing Density (by Adobe)",
  "Fujifilm ETERNA 400 Printing Density (by Adobe)",
  "Fujifilm ETERNA 500 Printing Density (by Adobe)",
  "Fujifilm ETERNA Vivid 160 Printing Density (by Adobe)",
  "Fujifilm F-125 Printing Density (by Adobe)",
  "Fujifilm F-64D Printing Density (by Adobe)",
  "Fujifilm REALA 500D Printing Density (by Adobe)",
  "Kodak 5205/7205 Printing Density (by Adobe)",
  "Kodak 5218/7218 Printing Density (by Adobe)",
  "Kodak 5229/7229 Printing Density (by Adobe)",
  "Universal Camera Film Printing Density",
  "ACEScct",
  "ARRI LogC3 Wide Color Gamut - EI 1000",
  "ARRI LogC3 Wide Color Gamut - EI 1280",
  "ARRI LogC3 Wide Color Gamut - EI 160",
  "ARRI LogC3 Wide Color Gamut - EI 1600",
  "ARRI LogC3 Wide Color Gamut - EI 200",
  "ARRI LogC3 Wide Color Gamut - EI 250",
  "ARRI LogC3 Wide Color Gamut - EI 320",
  "ARRI LogC3 Wide Color Gamut - EI 400",
  "ARRI LogC3 Wide Color Gamut - EI 500",
  "ARRI LogC3 Wide Color Gamut - EI 640",
  "ARRI LogC3 Wide Color Gamut - EI 800",
  "ARRI WCG Preview LUT for P3",
  "ARRI WCG Preview LUT for P3D65",
  "ARRI WCG Preview LUT for Rec. 709",
  "ARRIFLEX D-20 Daylight Log (by Adobe)",
  "ARRIFLEX D-20 Tungsten Log (by Adobe)",
  "Canon Cinema CLog2",
  "Canon Cinema CLog3",
  "Panasonic V-Gamut V-Log",
  "Panavision Genesis Tungsten Log (by Adobe)",
  "Rec.709 V-Log",
  "Sony S-Gamut3.Cine/S-Log3",
  "Sony S-Gamut3/S-Log3",
  "Viper FilmStream Daylight Log (by Adobe)",
  "Viper FilmStream Tungsten Log (by Adobe)",
  "Fujifilm 3510 (RDI) Theater Preview (by Adobe)",
  "Fujifilm 3513DI (RDI) Theater Preview (by Adobe)",
  "Fujifilm 3521XD (RDI) Theater Preview (by Adobe)",
  "Kodak 2383 Theater Preview 2 (by Adobe)",
  "Kodak 2393 Theater Preview 2 (by Adobe)",
  "Kodak 2395 Theater Preview 2 (by Adobe)",
  "(-",
  "ACES Academy Color Encoding Specification SMPTE ST 2065-1",
  "ACES CG Linear (Academy Color Encoding System AP1)",
  "ACEScct",
  "ACEScg ACES Working Space AMPAS S-2014-004",
  "ARRI LogC3 Wide Color Gamut - EI 1000",
  "ARRI LogC3 Wide Color Gamut - EI 1280",
  "ARRI LogC3 Wide Color Gamut - EI 160",
  "ARRI LogC3 Wide Color Gamut - EI 1600",
  "ARRI LogC3 Wide Color Gamut - EI 200",
  "ARRI LogC3 Wide Color Gamut - EI 250"
 ],
 "ADBE ProfileToProfile-0003": [
  "Project Working Space",
  "(-",
  "Adobe RGB (1998)",
  "Apple RGB",
  "ColorMatch RGB",
  "image P3",
  "ProPhoto RGB",
  "sRGB IEC61966-2.1",
  "(-",
  "Fujifilm ETERNA 250 Printing Density (by Adobe)",
  "Fujifilm ETERNA 250D Printing Density (by Adobe)",
  "Fujifilm ETERNA 400 Printing Density (by Adobe)",
  "Fujifilm ETERNA 500 Printing Density (by Adobe)",
  "Fujifilm ETERNA Vivid 160 Printing Density (by Adobe)",
  "Fujifilm F-125 Printing Density (by Adobe)",
  "Fujifilm F-64D Printing Density (by Adobe)",
  "Fujifilm REALA 500D Printing Density (by Adobe)",
  "Kodak 5205/7205 Printing Density (by Adobe)",
  "Kodak 5218/7218 Printing Density (by Adobe)",
  "Kodak 5229/7229 Printing Density (by Adobe)",
  "Universal Camera Film Printing Density",
  "ACEScct",
  "ARRI LogC3 Wide Color Gamut - EI 1000",
  "ARRI LogC3 Wide Color Gamut - EI 1280",
  "ARRI LogC3 Wide Color Gamut - EI 160",
  "ARRI LogC3 Wide Color Gamut - EI 1600",
  "ARRI LogC3 Wide Color Gamut - EI 200",
  "ARRI LogC3 Wide Color Gamut - EI 250",
  "ARRI LogC3 Wide Color Gamut - EI 320",
  "ARRI LogC3 Wide Color Gamut - EI 400",
  "ARRI LogC3 Wide Color Gamut - EI 500",
  "ARRI LogC3 Wide Color Gamut - EI 640",
  "ARRI LogC3 Wide Color Gamut - EI 800",
  "ARRI WCG Preview LUT for P3",
  "ARRI WCG Preview LUT for P3D65",
  "ARRI WCG Preview LUT for Rec. 709",
  "ARRIFLEX D-20 Daylight Log (by Adobe)",
  "ARRIFLEX D-20 Tungsten Log (by Adobe)",
  "Canon Cinema CLog2",
  "Canon Cinema CLog3",
  "Panasonic V-Gamut V-Log",
  "Panavision Genesis Tungsten Log (by Adobe)",
  "Rec.709 V-Log",
  "Sony S-Gamut3.Cine/S-Log3",
  "Sony S-Gamut3/S-Log3",
  "Viper FilmStream Daylight Log (by Adobe)",
  "Viper FilmStream Tungsten Log (by Adobe)",
  "(-",
  "ACES Academy Color Encoding Specification SMPTE ST 2065-1",
  "ACES CG Linear (Academy Color Encoding System AP1)",
  "ACEScct",
  "ACEScg ACES Working Space AMPAS S-2014-004",
  "ARRI LogC3 Wide Color Gamut - EI 1000",
  "ARRI LogC3 Wide Color Gamut - EI 1280",
  "ARRI LogC3 Wide Color Gamut - EI 160",
  "ARRI LogC3 Wide Color Gamut - EI 1600",
  "ARRI LogC3 Wide Color Gamut - EI 200",
  "ARRI LogC3 Wide Color Gamut - EI 250",
  "ARRI LogC3 Wide Color Gamut - EI 320",
  "ARRI LogC3 Wide Color Gamut - EI 400",
  "ARRI LogC3 Wide Color Gamut - EI 500",
  "ARRI LogC3 Wide Color Gamut - EI 640",
  "ARRI LogC3 Wide Color Gamut - EI 800",
  "ARRI WCG Preview LUT for P3"
 ],
 "ADBE ProfileToProfile-0005": [
  "Perceptual",
  "Saturation",
  "Relative Colorimetric",
  "Absolute Colorimetric"
 ],
 "ADBE ProfileToProfile-0007": [
  "Use Project Setting",
  "On",
  "Off"
 ],
 "ADBE Radial Shadow-0006": [
  "Regular",
  "Glass Edge"
 ],
 "ADBE Radial Blur-0003": [
  "Spin",
  "Zoom"
 ],
 "ADBE Radial Blur-0004": [
  "Low",
  "High"
 ],
 "ADBE Radial Wipe-0004": [
  "Clockwise",
  "Counterclockwise",
  "Both"
 ],
 "APC Radio Waves-0006": [
  "Birth",
  "Each Frame"
 ],
 "APC Radio Waves-0002": [
  "Polygon",
  "Image Contours",
  "Mask"
 ],
 "APC Radio Waves-0022": [
  "Intensity",
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Hue",
  "Lightness",
  "Saturation",
  "Value"
 ],
 "APC Radio Waves-0048": [
  "Square",
  "Triangle",
  "Sawtooth Out",
  "Sawtooth In",
  "Gaussian",
  "Bell",
  "Sine"
 ],
 "ADBE Ramp-0005": [
  "Linear Ramp",
  "Radial Ramp"
 ],
 "ADBE RESHAPE-0005": [
  "Stiff",
  "Less Stiff",
  "Below Normal",
  "Normal",
  "Absolutely Normal",
  "Above Average",
  "Loose",
  "Liquid",
  "Super Fluid"
 ],
 "ADBE RESHAPE-0009": [
  "Discrete",
  "Linear",
  "Smooth"
 ],
 "ADBE Ripple-0003": [
  "Asymmetric",
  "Symmetric"
 ],
 "ADBE OFMotionBlur-0001": [
  "Manual",
  "Automatic"
 ],
 "ADBE Rolling Shutter-0002": [
  "Top -> Bottom",
  "Bottom -> Top",
  "Left -> Right",
  "Right -> Left"
 ],
 "ADBE Rolling Shutter-0004": [
  "Warp",
  "Pixel Motion"
 ],
 "ADBE Timewarp-0001": [
  "Whole Frames",
  "Frame Mix",
  "Pixel Motion"
 ],
 "ADBE Timewarp-0002": [
  "Speed",
  "Source Frame"
 ],
 "ADBE Timewarp-0014": [
  "Normal",
  "Extreme"
 ],
 "ADBE Timewarp-0025": [
  "Manual",
  "Automatic"
 ],
 "ADBE Timewarp-0030": [
  "Luminance",
  "Inverted Luminance",
  "Alpha",
  "Inverted Alpha"
 ],
 "ADBE Timewarp-0032": [
  "Normal",
  "Matte",
  "Foreground",
  "Background"
 ],
 "ADBE Roughen Edges-0001": [
  "Roughen",
  "Roughen Color",
  "Cut",
  "Spiky",
  "Rusty",
  "Rusty Color",
  "Photocopy",
  "Photocopy Color"
 ],
 "ADBE Scatter-0002": [
  "Both",
  "Horizontal",
  "Vertical"
 ],
 "ADBE Scribble Fill-0064": [
  "None",
  "(-",
  "Single Mask",
  "All Masks",
  "All Masks Using Modes"
 ],
 "ADBE Scribble Fill-0050": [
  "Inside",
  "Centered Edge",
  "Inside Edge",
  "Outside Edge",
  "Left Edge",
  "Right Edge"
 ],
 "ADBE Scribble Fill-0056": [
  "Round",
  "Butt",
  "Projecting"
 ],
 "ADBE Scribble Fill-0054": [
  "Round",
  "Bevel",
  "Miter"
 ],
 "ADBE Scribble Fill-0068": [
  "Mask Path",
  "Scribble Result"
 ],
 "ADBE Scribble Fill-0048": [
  "Static",
  "Jumpy",
  "Smooth"
 ],
 "ADBE Scribble Fill-0026": [
  "On Original Image",
  "On Transparent",
  "Reveal Original Image"
 ],
 "ADBE Set Channels-0002": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Off"
 ],
 "ADBE Set Channels-0004": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Off"
 ],
 "ADBE Set Channels-0006": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Off"
 ],
 "ADBE Set Channels-0008": [
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Off"
 ],
 "ADBE Set Matte3-0002": [
  "Red Channel",
  "Green Channel",
  "Blue Channel",
  "Alpha Channel",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Off"
 ],
 "ADBE Set Matte2-0002": [
  "Red Channel",
  "Green Channel",
  "Blue Channel",
  "Alpha Channel",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full",
  "Off"
 ],
 "ADBE Camera Lens Blur-0003": [
  "Triangle",
  "Square",
  "Pentagon",
  "Hexagon",
  "Heptagon",
  "Octagon",
  "Nonagon",
  "Decagon"
 ],
 "ADBE Camera Lens Blur-0011": [
  "Luminance",
  "Red",
  "Green",
  "Blue",
  "Alpha"
 ],
 "ADBE Camera Lens Blur-0012": [
  "Center Map",
  "Stretch Map to Fit"
 ],
 "APC Shatter-0002": [
  "Rendered",
  "Wireframe Front View ",
  "Wireframe",
  "Wireframe Front View + Forces",
  "Wireframe + Forces"
 ],
 "APC Shatter-0004": [
  "All",
  "Layer",
  "Pieces"
 ],
 "APC Shatter-0006": [
  "Custom",
  "(-",
  "Bricks",
  "Carpenter\u2019s Wheel",
  "Chevrons",
  "Crescents",
  "Eggs",
  "Glass",
  "Herringbone 1",
  "Herringbone 2",
  "Hexagons",
  "Js",
  "Octagons & Squares",
  "Overlaid Squares",
  "Planks",
  "Puzzle",
  "Rhombi",
  "Squares",
  "Squares & Triangles",
  "Stars & Triangles",
  "Triangles 1",
  "Triangles 2"
 ],
 "APC Shatter-0042": [
  "Free",
  "None",
  "X",
  "Y",
  "Z",
  "XY",
  "XZ",
  "YZ"
 ],
 "APC Shatter-0060": [
  "Color",
  "Layer",
  "Tinted Layer",
  "Color + Opacity",
  "Layer + Opacity",
  "Tinted Layer + Opacity"
 ],
 "APC Shatter-0064": [
  "Color",
  "Layer",
  "Tinted Layer",
  "Color + Opacity",
  "Layer + Opacity",
  "Tinted Layer + Opacity"
 ],
 "APC Shatter-0068": [
  "Color",
  "Layer",
  "Tinted Layer",
  "Color + Opacity",
  "Layer + Opacity",
  "Tinted Layer + Opacity"
 ],
 "APC Shatter-0072": [
  "Camera Position",
  "Corner Pins",
  "Comp Camera"
 ],
 "APC Shatter-0086": [
  "Rotate XYZ, Position",
  "Rotate XZY, Position",
  "Rotate YXZ, Position",
  "Rotate YZX, Position",
  "Rotate ZXY, Position",
  "Rotate ZYX, Position",
  "Position, Rotate XYZ",
  "Position, Rotate XZY",
  "Position, Rotate YXZ",
  "Position, Rotate YZX",
  "Position, Rotate ZXY",
  "Position, Rotate ZYX"
 ],
 "APC Shatter-0108": [
  "Point Source",
  "Distant Source",
  "First Comp Light"
 ],
 "ADBE Shift Channels-0001": [
  "Alpha",
  "Red",
  "Green",
  "Blue",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full On",
  "Full Off"
 ],
 "ADBE Shift Channels-0002": [
  "Alpha",
  "Red",
  "Green",
  "Blue",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full On",
  "Full Off"
 ],
 "ADBE Shift Channels-0003": [
  "Alpha",
  "Red",
  "Green",
  "Blue",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full On",
  "Full Off"
 ],
 "ADBE Shift Channels-0004": [
  "Alpha",
  "Red",
  "Green",
  "Blue",
  "Luminance",
  "Hue",
  "Lightness",
  "Saturation",
  "Full On",
  "Full Off"
 ],
 "ADBE Simple Choker-0001": [
  "Final Output",
  "Matte"
 ],
 "ADBE Smart Blur-0003": [
  "Normal",
  "Edge Only",
  "Overlay Edge"
 ],
 "ADBE SCHMEAR-0007": [
  "Stiff",
  "Less Stiff",
  "Below Normal",
  "Normal",
  "Absolutely Normal",
  "Above Average",
  "Loose",
  "Liquid",
  "Super Fluid"
 ],
 "ADBE SCHMEAR-0008": [
  "Discrete",
  "Linear",
  "Smooth"
 ],
 "ADBE Solid Composite-0004": [
  "Normal",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Color",
  "Luminosity"
 ],
 "ADBE Spill2-0001": [
  "Standard",
  "Ultra"
 ],
 "ADBE Strobe-0006": [
  "Operates On Color Only",
  "Makes Layer Transparent"
 ],
 "ADBE Strobe-0007": [
  "Copy",
  "Add",
  "Subtract",
  "Multiply",
  "Difference",
  "And",
  "Or",
  "Xor",
  "Lighter",
  "Darker",
  "Minimum",
  "Maximum",
  "Screen"
 ],
 "ADBE Stroke-0007": [
  "On Original Image",
  "On Transparent",
  "Reveal Original Image"
 ],
 "ADBE Texturize-0004": [
  "Tile Texture",
  "Center Texture",
  "Stretch Texture to Fit"
 ],
 "ADBE Three-Way Color Corrector-0001": [
  "Composite",
  "Luma",
  "Mask",
  "Tonal Range"
 ],
 "ADBE Three-Way Color Corrector-0003": [
  "Horizontal",
  "Vertical"
 ],
 "ADBE Three-Way Color Corrector-0119": [
  "None",
  "Invert Limit Color",
  "Invert Mask"
 ],
 "ADBE Timecode-0002": [
  "SMPTE HH:MM:SS:FFF",
  "Frame numbers",
  "Feet + Frames (35mm)",
  "Feet + Frames (16mm)"
 ],
 "ADBE Timecode-0009": [
  "Layer Source",
  "Composition",
  "Custom"
 ],
 "ADBE Geometry-0012": [
  "Bilinear",
  "Bicubic"
 ],
 "ADBE Geometry2-0012": [
  "Bilinear",
  "Bicubic"
 ],
 "ADBE Turbulent Displace-0001": [
  "Turbulent",
  "Bulge",
  "Twist",
  "(-",
  "Turbulent Smoother",
  "Bulge Smoother",
  "Twist Smoother",
  "(-",
  "Vertical Displacement",
  "Horizontal Displacement",
  "Cross Displacement"
 ],
 "ADBE Turbulent Displace-0012": [
  "None",
  "(-",
  "Pin All",
  "Pin Horizontal",
  "Pin Vertical",
  "Pin Left",
  "Pin Right",
  "Pin Top",
  "Pin Bottom",
  "(-",
  "Pin All Locked",
  "Pin Horizontal Locked",
  "Pin Vertical Locked",
  "Pin Left Locked",
  "Pin Right Locked",
  "Pin Top Locked",
  "Pin Bottom Locked"
 ],
 "ADBE Turbulent Displace-0014": [
  "Low",
  "High"
 ],
 "ADBE AIF Perlin Noise 3D-0001": [
  "Basic",
  "(-",
  "Turbulent Smooth",
  "Turbulent Basic",
  "Turbulent Sharp",
  "(-",
  "Dynamic",
  "Dynamic Progressive",
  "Dynamic Twist",
  "(-",
  "Max",
  "Smeary",
  "Swirly",
  "Rocky",
  "Cloudy",
  "Terrain",
  "Subscale",
  "Small Bumps",
  "Strings",
  "Threads"
 ],
 "ADBE AIF Perlin Noise 3D-0002": [
  "Block",
  "Linear",
  "Soft Linear",
  "Spline"
 ],
 "ADBE AIF Perlin Noise 3D-0006": [
  "Clip",
  "Soft Clamp",
  "Wrap Back",
  "Allow HDR Results"
 ],
 "ADBE AIF Perlin Noise 3D-0026": [
  "None",
  "Normal",
  "(-",
  "Add",
  "Multiply",
  "Screen",
  "Overlay",
  "Soft Light",
  "Hard Light",
  "(-",
  "Color Dodge",
  "Color Burn",
  "(-",
  "Darken",
  "Lighten",
  "Difference",
  "Exclusion",
  "(-",
  "Hue",
  "Saturation",
  "Luminosity"
 ],
 "ADBE Unmult-0030": [
  "Black",
  "White"
 ],
 "ADBE Upscale-0005": [
  "Detail-preserving",
  "Bicubic"
 ],
 "APC Vegas-0052": [
  "Image Contours",
  "Mask/Path"
 ],
 "APC Vegas-0006": [
  "Center",
  "Stretch to Fit"
 ],
 "APC Vegas-0010": [
  "Intensity",
  "Red",
  "Green",
  "Blue",
  "Alpha",
  "Hue",
  "Lightness",
  "Saturation",
  "Value"
 ],
 "APC Vegas-0044": [
  "All Contours",
  "Selected Contour"
 ],
 "APC Vegas-0048": [
  "Same Number of Segments",
  "Fewer Segments"
 ],
 "APC Vegas-0026": [
  "Bunched",
  "Even"
 ],
 "APC Vegas-0008": [
  "Transparent",
  "Over",
  "Under",
  "Stencil"
 ],
 "ADBE DigitalVideoLimiter-0002": [
  "None",
  "3%",
  "5%",
  "10%",
  "20%"
 ],
 "APC Wave World-0002": [
  "Height Map",
  "Wireframe Preview"
 ],
 "APC Wave World-0016": [
  "Solid",
  "Transparent"
 ],
 "APC Wave World-0020": [
  "None",
  "All",
  "Left",
  "Top",
  "Right",
  "Bottom",
  "Left & Top",
  "Right & Left",
  "Right & Top",
  "Bottom & Left",
  "Bottom & Top",
  "Bottom & Right",
  "Right & Left & Top",
  "Bottom & Left & Top",
  "Bottom & Right & Left",
  "Bottom & Right & Top"
 ],
 "APC Wave World-0042": [
  "Ring",
  "Line"
 ],
 "APC Wave World-0058": [
  "Ring",
  "Line"
 ],
 "ADBE Wave Warp-0001": [
  "Sine",
  "Square",
  "Triangle",
  "Sawtooth",
  "Circle",
  "Semicircle",
  "Uncircle",
  "Noise",
  "Smooth Noise"
 ],
 "ADBE Wave Warp-0006": [
  "None",
  "All Edges",
  "Center",
  "(-",
  "Left Edge",
  "Top Edge",
  "Right Edge",
  "Bottom Edge",
  "(-",
  "Horizontal Edges",
  "Vertical Edges"
 ],
 "ADBE Wave Warp-0008": [
  "Low",
  "Medium",
  "High"
 ],
 "ADBE Write-on-0008": [
  "None",
  "Opacity",
  "Color"
 ],
 "ADBE Write-on-0009": [
  "None",
  "Size",
  "Hardness",
  "Size & Hardness"
 ],
 "ADBE Write-on-0010": [
  "On Original Image",
  "On Transparent",
  "Reveal Original Image"
 ],
 "ADBE FreePin3 Puppet Engine": [
  "Legacy",
  "Advanced"
 ],
 "ADBE RefineMatte2-0035": [
  "Off",
  "(-",
  "More Detailed",
  "Smoother (Slower)"
 ],
 "ADBE Stereo 3D Controls-0002": [
  "Center",
  "Hero Left",
  "Hero Right"
 ],
 "ADBE Stereo 3D Controls-0007": [
  "Camera Position",
  "Camera Point of Interest",
  "Zoom Distance"
 ]
};
